/* Generated By:JJTree&JavaCC: Do not edit this line. FoodConstants.java */
package Food;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface FoodConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int TPINTEIRO = 5;
  /** RegularExpression Id. */
  int TPBOOLEAN = 6;
  /** RegularExpression Id. */
  int TPSTRING = 7;
  /** RegularExpression Id. */
  int TPREAL = 8;
  /** RegularExpression Id. */
  int INICIOPROGRAMA = 9;
  /** RegularExpression Id. */
  int ABREBLOCO = 10;
  /** RegularExpression Id. */
  int FECHABLOCO = 11;
  /** RegularExpression Id. */
  int ABREBLOCOND = 12;
  /** RegularExpression Id. */
  int FECHABLOCOND = 13;
  /** RegularExpression Id. */
  int CONDIF = 14;
  /** RegularExpression Id. */
  int CONDELSE = 15;
  /** RegularExpression Id. */
  int REPWHILE = 16;
  /** RegularExpression Id. */
  int REPFOR = 17;
  /** RegularExpression Id. */
  int ENTAO = 18;
  /** RegularExpression Id. */
  int NUMERO = 19;
  /** RegularExpression Id. */
  int DIGITO = 20;
  /** RegularExpression Id. */
  int ID = 21;
  /** RegularExpression Id. */
  int LETRA = 22;
  /** RegularExpression Id. */
  int BOOL = 23;
  /** RegularExpression Id. */
  int ASPAS = 24;
  /** RegularExpression Id. */
  int FIM_STRUC = 25;
  /** RegularExpression Id. */
  int DIFERENTE = 26;
  /** RegularExpression Id. */
  int MENORIGUAL = 27;
  /** RegularExpression Id. */
  int MAIORIGUAL = 28;
  /** RegularExpression Id. */
  int IGUAL = 29;
  /** RegularExpression Id. */
  int E = 30;
  /** RegularExpression Id. */
  int OU = 31;
  /** RegularExpression Id. */
  int MAIS = 32;
  /** RegularExpression Id. */
  int MENOS = 33;
  /** RegularExpression Id. */
  int MULTI = 34;
  /** RegularExpression Id. */
  int DIV = 35;
  /** RegularExpression Id. */
  int MAIOR = 36;
  /** RegularExpression Id. */
  int MENOR = 37;
  /** RegularExpression Id. */
  int ATRIBUI = 38;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"torrada\"",
    "\"processado\"",
    "\"macarronada\"",
    "\"agua\"",
    "\"prato\"",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\"almoco\"",
    "\"sobremesa\"",
    "\"rodizio\"",
    "\"degustacao\"",
    "\"coma\"",
    "<NUMERO>",
    "<DIGITO>",
    "<ID>",
    "<LETRA>",
    "<BOOL>",
    "\"\\\'\"",
    "\".\"",
    "\"!=\"",
    "\"<=\"",
    "\">=\"",
    "\"==\"",
    "\"&&\"",
    "\"||\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\">\"",
    "\"<\"",
    "\"=\"",
  };

}
