/* Generated By:JavaCC: Do not edit this line. FoodTreeConstants.java Version 7.0.12 */
package Food;

public interface FoodTreeConstants
{
  public int JJTMAIN = 0;
  public int JJTOPERACAO_MATEMATICA = 1;
  public int JJTCOMPARACAO = 2;
  public int JJTOPERACAO_LOGICA = 3;
  public int JJTBODY = 4;
  public int JJTDECLARA_VARIAVEL = 5;
  public int JJTCOND = 6;
  public int JJTATRIBUICAOVAR = 7;
  public int JJTINICIOPROGRAMA = 8;
  public int JJTABREBLOCO = 9;
  public int JJTTIPOS = 10;
  public int JJTFECHABLOCO = 11;
  public int JJTENTAO = 12;
  public int JJTREPFOR = 13;
  public int JJTREPWHILE = 14;
  public int JJTCONDIF = 15;
  public int JJTCONDELSE = 16;
  public int JJTENTRADA = 17;
  public int JJTFECHABLOCOCOND = 18;
  public int JJTABREBLOCOCOND = 19;
  public int JJTTPSTRING = 20;
  public int JJTTPINTEIRO = 21;
  public int JJTTPBOOLEAN = 22;
  public int JJTFIMSTRUCT = 23;
  public int JJTID = 24;
  public int JJTASPAS = 25;
  public int JJTATRIBUI = 26;
  public int JJTNUMERO = 27;


  public String[] jjtNodeName = {
    "main",
    "operacao_matematica",
    "comparacao",
    "operacao_logica",
    "body",
    "declara_variavel",
    "cond",
    "atribuicaoVar",
    "inicioPrograma",
    "abreBloco",
    "tipos",
    "fechaBloco",
    "entao",
    "repFor",
    "repWhile",
    "condIf",
    "condElse",
    "entrada",
    "fechaBlocoCond",
    "abreBlocoCond",
    "tpString",
    "tpInteiro",
    "tpBoolean",
    "fimStruct",
    "id",
    "aspas",
    "atribui",
    "numero",
  };
}
/* JavaCC - OriginalChecksum=adca1b2b5fe06a8f1d1e84436c498cdf (do not edit this line) */
